import './globals.css'
import type { Metadata } from 'next'
// import SessionProvider from "./SessionProvider"
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Logi-Tech',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {


  
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     {/* <SessionProvider> */}
      <body className={inter.className}>{children}
      </body>
      {/* </SessionProvider>  */}
    </html>

  )
}
